spring:
  application:
    name: ai-knowledge-service

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  ai:
    model:
      embedding: ollama

    ollama:
      base-url: http://localhost:11434

      embedding:
        options:
          model: bge-m3
server:
  port: 8081
